

package AbstractProductA;



import java.awt.event.KeyEvent;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.JButton;
import javax.swing.JTextField;

// Promenljivo!!!
public class Panel2 extends Panel{

    /**
     * Creates new form Panel1
     */
    public Panel2() {
        initComponents();
        prepared();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbVoce = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        SifraPorudzbine = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Kreiraj = new javax.swing.JButton();
        Promeni = new javax.swing.JButton();
        Obrisi = new javax.swing.JButton();
        Nadji = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        Poruka = new javax.swing.JTextField();
        cmbPalacinka = new javax.swing.JComboBox<>();
        cmbPreliv = new javax.swing.JComboBox<>();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmbVoce.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "5", "6", "7", "8", "9", "10" }));
        cmbVoce.setEditor(null);
        cmbVoce.setName("cmbVoce"); // NOI18N
        cmbVoce.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cmbVoceKeyPressed(evt);
            }
        });
        add(cmbVoce, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 120, -1));

        jLabel1.setText("Palacinka:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel2.setText("Preliv:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel3.setText("Voce:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        SifraPorudzbine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SifraPorudzbineActionPerformed(evt);
            }
        });
        SifraPorudzbine.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                SifraPorudzbineKeyPressed(evt);
            }
        });
        add(SifraPorudzbine, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 54, -1));

        jLabel4.setText("Sifra porudzbine");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        Kreiraj.setText("Kreiraj");
        add(Kreiraj, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        Promeni.setText("Promeni");
        add(Promeni, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, -1));

        Obrisi.setText("Obrisi");
        add(Obrisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, -1, -1));

        Nadji.setText("Nadji");
        Nadji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NadjiActionPerformed(evt);
            }
        });
        add(Nadji, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel6.setText("Poruka:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 45, -1));

        Poruka.setForeground(new java.awt.Color(255, 0, 0));
        Poruka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PorukaActionPerformed(evt);
            }
        });
        add(Poruka, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 250, -1));

        cmbPalacinka.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(cmbPalacinka, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 120, -1));

        cmbPreliv.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(cmbPreliv, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 120, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void cmbVoceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmbVoceKeyPressed
         if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
                SifraPorudzbine.requestFocus();
          } // TODO add your handling code here:
    }//GEN-LAST:event_cmbVoceKeyPressed

    private void SifraPorudzbineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SifraPorudzbineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SifraPorudzbineActionPerformed

    private void NadjiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NadjiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NadjiActionPerformed

    private void PorukaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PorukaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PorukaActionPerformed

    private void SifraPorudzbineKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SifraPorudzbineKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
                SifraPorudzbine.requestFocusInWindow();
          }
    }//GEN-LAST:event_SifraPorudzbineKeyPressed

       
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Kreiraj;
    private javax.swing.JButton Nadji;
    private javax.swing.JButton Obrisi;
    private javax.swing.JTextField Poruka;
    private javax.swing.JButton Promeni;
    private javax.swing.JTextField SifraPorudzbine;
    private javax.swing.JComboBox<String> cmbPalacinka;
    private javax.swing.JComboBox<String> cmbPreliv;
    private javax.swing.JComboBox<String> cmbVoce;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables

    @Override
    public String getSifraPorudzbine() {
        return SifraPorudzbine.getText();
    }

    @Override
    public JTextField getSifraPorudzbine1() {
        return SifraPorudzbine;
    }

    @Override
    public String getPalacinka() {
        return cmbPalacinka.getSelectedItem().toString();
                
    }

    @Override
    public String getPreliv() {
        return cmbPreliv.getSelectedItem().toString();
    }

    @Override
    public String getVoce() {
        return cmbVoce.getSelectedItem().toString();
    }

    @Override
    public void setSifraPorudzbine(String sifraPorudzbine) {
        SifraPorudzbine.setText(sifraPorudzbine);
    }

    @Override
    public void setPalacinka(String Palacinka) {
        cmbPalacinka.setSelectedItem(Palacinka);
    }

    @Override
    public void setPreliv(String Preliv) {
        cmbPreliv.setSelectedItem(Preliv);
    }

    @Override
    public void setVoce(String Voce) {
        cmbVoce.setSelectedItem(Voce);
    }

    @Override
    public void setPoruka(String Poruka) {
        this.Poruka.setText(Poruka);
    }

    @Override
    public JButton getKreiraj() {
        return Kreiraj;
    }

    @Override
    public JButton getPromeni() {
        return Promeni;
    }

    @Override
    public JButton getObrisi() {
        return Obrisi;
    }

    @Override
    public JButton getNadji() {
        return Nadji;
    }

    private void prepared() {
        cmbPalacinka.removeAllItems();
        cmbPalacinka.addItem("COKO");
        cmbPalacinka.addItem("KLASICNA");
        cmbPalacinka.addItem("RED VELVET");
        
        cmbVoce.removeAllItems();
        cmbVoce.addItem("banana");
        cmbVoce.addItem("visnje");
        cmbVoce.addItem("sumsko voce");
        
        cmbPreliv.removeAllItems();
        cmbPreliv.addItem("Nutela");
        cmbPreliv.addItem("Ala Kinder Bueno");
        cmbPreliv.addItem("Gold bela cokolada");
    }
}
